# Generated by Django 4.1 on 2023-10-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_application_creator_alter_application_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Создана'), ('processed', 'Обрабатывается'), ('coordination', 'На согласовании у заказчика'), ('payment_coordination', 'Ожидается оплата'), ('in_work', 'Передано исполнителю'), ('finished', 'Выполнено')], default='new', max_length=50, verbose_name='Статус заявки'),
        ),
    ]
