# Generated by Django 4.1 on 2023-10-11 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_application_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='end_work_date',
            new_name='endWorkDate',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='start_work_date',
            new_name='startWorkDate',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='total_summ',
            new_name='totalSum',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='total_summ_with_percent',
            new_name='totalSumWithPercent',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='work_materials',
            new_name='workMaterials',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='work_tasks',
            new_name='workTasks',
        ),
        migrations.AlterField(
            model_name='application',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicationCreator', to='api.employee', verbose_name='Создатель заявки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='performer',
            field=models.ManyToManyField(blank=True, null=True, related_name='applicationPerformer', to='api.employee', verbose_name='Исполнители'),
        ),
    ]
