# Generated by Django 4.1 on 2023-10-11 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_created_at_application_createdat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='legal_entity',
            new_name='legalEntity',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='work_object',
            new_name='workObject',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='work_objects_group',
            new_name='workObjectsGroup',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='doc_type',
            new_name='docType',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='legal_entity',
            new_name='legalEntity',
        ),
        migrations.RenameField(
            model_name='legalentity',
            old_name='actual_address',
            new_name='actualAddress',
        ),
        migrations.RenameField(
            model_name='legalentity',
            old_name='correspondent_account',
            new_name='correspondentAccount',
        ),
        migrations.RenameField(
            model_name='legalentity',
            old_name='legal_address',
            new_name='legalAddress',
        ),
        migrations.RenameField(
            model_name='legalentity',
            old_name='settlement_account',
            new_name='settlementAccount',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='founded_apllications',
            new_name='foundedApllications',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='period_end',
            new_name='periodEnd',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='period_start',
            new_name='periodStart',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='workobject',
            old_name='contract_number',
            new_name='contractNumber',
        ),
        migrations.RenameField(
            model_name='workobjectsgroup',
            old_name='work_objects',
            new_name='workObjects',
        ),
    ]
