# Generated by Django 4.1 on 2023-10-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_workmaterial_options_alter_worktask_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workmaterialgroup',
            old_name='tasks',
            new_name='materials',
        ),
    ]
