# Generated by Django 4.1 on 2023-10-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_worktaskgroup_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workmaterialgroup',
            name='materials',
            field=models.ManyToManyField(blank=True, to='api.workmaterial', verbose_name='Список материалов входящих в эту группу'),
        ),
    ]
