# Generated by Django 4.1 on 2023-10-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_workmaterialgroup_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workmaterial',
            name='actualCount',
        ),
        migrations.RemoveField(
            model_name='workmaterial',
            name='summ',
        ),
        migrations.RemoveField(
            model_name='worktask',
            name='actualTime',
        ),
        migrations.RemoveField(
            model_name='worktask',
            name='summ',
        ),
        migrations.AlterField(
            model_name='workmaterialgroup',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='workMaterialGroup', to='api.workmaterial', verbose_name='Список материалов входящих в эту группу'),
        ),
        migrations.AlterField(
            model_name='worktaskgroup',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='workTaskGroup', to='api.worktask', verbose_name='Список услуг входящих в эту группу'),
        ),
    ]
