# Generated by Django 4.1 on 2023-10-16 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_workmaterial_actualcount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workmaterial',
            old_name='pirce',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='worktask',
            old_name='pirce',
            new_name='price',
        ),
    ]
