# Generated by Django 4.1 on 2023-10-21 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_pirce_workmaterial_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='workMaterials',
        ),
        migrations.RemoveField(
            model_name='application',
            name='workTasks',
        ),
        migrations.CreateModel(
            name='ApplicationWorkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualTime', models.PositiveIntegerField(blank=True, null=True, verbose_name='Актуальное время')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.application')),
                ('work_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.worktask')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationWorkMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualCount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Действительное количество')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.application')),
                ('work_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.workmaterial')),
            ],
        ),
    ]
