# Generated by Django 4.1 on 2023-10-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_application_workmaterials_application_worktasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationworkmaterial',
            old_name='work_material',
            new_name='workMaterial',
        ),
        migrations.RenameField(
            model_name='applicationworktask',
            old_name='work_task',
            new_name='workTask',
        ),
    ]
