# Generated by Django 4.1 on 2023-10-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_work_material_applicationworkmaterial_workmaterial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Место выполнения заявки'),
        ),
    ]
