# Generated by Django 4.1 on 2023-11-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_legalentity_swatzki_legalentity_sawatzki'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='documents/', verbose_name='Файл документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='docType',
            field=models.CharField(choices=[('Act', 'Акт'), ('Power_of_attorney', 'Доверенность'), ('Payment_slip', 'Платежка'), ('Other', 'Прочее')], max_length=32, verbose_name='Тип документа'),
        ),
    ]
