# Generated by Django 4.1 on 2023-11-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_document_file_alter_document_doctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, default=1, null=True, upload_to='documents/', verbose_name='Файл документа'),
        ),
    ]
