# Generated by Django 4.1 on 2023-11-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_created_at_document_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='sawatzkyemployee',
            name='group',
            field=models.CharField(choices=[('S1', 'Управляющий Объекта'), ('S2', 'Руководитель Отдела Управления'), ('S3', 'Исполнительный директор'), ('S4', 'Руководство'), ('S5', 'Администратор системы'), ('S6', 'Разработчик системы')], default='S1', max_length=20, verbose_name='Группа пользователя Sawatzky'),
        ),
        migrations.AddField(
            model_name='sawatzkyemployee',
            name='role',
            field=models.CharField(choices=[('dispatcher', 'Диспетчер'), ('performer', 'Исполнитель'), ('dispatcherPerformer', 'Диспетчер/Исполнитель')], default='user', max_length=20, verbose_name='Роль пользователя Sawatzky'),
        ),
    ]
