# Generated by Django 4.1 on 2023-11-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_sawatzkyemployee_group_sawatzkyemployee_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='workObjectsGroup',
        ),
        migrations.AddField(
            model_name='client',
            name='workObjectsGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='api.workobjectsgroup', verbose_name='Группы рабочих объектов'),
        ),
    ]
