# Generated by Django 4.1 on 2023-11-30 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_legalentity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='prepayment',
            field=models.BooleanField(default=False, verbose_name='Работа по предоплате'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='workMaterialGroups',
            field=models.ManyToManyField(blank=True, null=True, to='api.workmaterialgroup', verbose_name='Предоставляемые группы материалов'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='workObject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='api.workobject', verbose_name='Рабочий объект'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='workObjectsGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='api.workobjectsgroup', verbose_name='Группы рабочих объектов'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='workTaskGroups',
            field=models.ManyToManyField(blank=True, null=True, to='api.worktaskgroup', verbose_name='Предоставляемые группы услуг'),
        ),
        migrations.AlterField(
            model_name='report',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.legalentity', verbose_name='Заказчик в рамках которого создается отчет'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
