# Generated by Django 4.1 on 2023-12-01 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_legalentity_prepayment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legalentity',
            old_name='sawatzki',
            new_name='sawatzky',
        ),
    ]
