# Generated by Django 4.1 on 2023-12-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_sawatzki_legalentity_sawatzky'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='powerOfAttorneyNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер доверенности'),
        ),
    ]
