# Generated by Django 4.1 on 2023-12-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_document_signed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('initiator', 'Инициатор')], default='user', max_length=20, verbose_name='Роль пользователя'),
        ),
        migrations.AlterField(
            model_name='sawatzkyemployee',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('dispatcher', 'Диспетчер'), ('performer', 'Исполнитель'), ('dispatcherPerformer', 'Диспетчер/Исполнитель')], default='user', max_length=20, verbose_name='Роль пользователя Sawatzky'),
        ),
    ]
