# Generated by Django 4.1 on 2023-12-12 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_applicationperformer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationEmployee',
        ),
    ]
