# Generated by Django 4.1 on 2023-12-12 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_application_performer_applicationperformer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationEmployee',
        ),
    ]
