# Generated by Django 4.1 on 2023-12-12 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_applicationperformer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationPerformer',
        ),
    ]
