# Generated by Django 4.1 on 2023-12-12 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_delete_applicationperformer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationPerformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='performers',
            field=models.ManyToManyField(blank=True, null=True, related_name='application', through='api.ApplicationPerformer', to='api.employee', verbose_name='Проводимые работы'),
        ),
        migrations.AddField(
            model_name='applicationperformer',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.application'),
        ),
        migrations.AddField(
            model_name='applicationperformer',
            name='performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
    ]
