# Generated by Django 4.1 on 2023-12-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_applicationperformer_application_performers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationperformer',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Срочно'), ('notUrgent', 'Не срочно')], default='urgent', max_length=20, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='applicationperformer',
            name='status',
            field=models.CharField(choices=[('accepted', 'Принял'), ('notAccepted', 'Не принял'), ('declined', 'Отказался'), ('completed', 'Выполнил')], default='notAccepted', max_length=20, verbose_name='Стаус'),
        ),
        migrations.AlterField(
            model_name='application',
            name='performers',
            field=models.ManyToManyField(blank=True, null=True, related_name='application', through='api.ApplicationPerformer', to='api.employee', verbose_name='Исполнители'),
        ),
    ]
