# Generated by Django 4.1 on 2023-12-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_applicationperformer_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationperformer',
            name='dateAccepted',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата принятия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationperformer',
            name='dateDeclined',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата отказа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationperformer',
            name='dateSent',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата отправки'),
            preserve_default=False,
        ),
    ]
