# Generated by Django 4.1 on 2023-12-13 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_applicationperformer_dateaccepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationperformer',
            name='dateSent',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 13, 21, 46, 0, 717912, tzinfo=datetime.timezone.utc), verbose_name='Дата отправки'),
            preserve_default=False,
        ),
    ]
