# Generated by Django 4.1 on 2023-12-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_applicationperformer_datesent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationperformer',
            name='dateAccepted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия'),
        ),
        migrations.AlterField(
            model_name='applicationperformer',
            name='dateDeclined',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отказа'),
        ),
    ]
