# Generated by Django 4.1 on 2023-12-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_applicationperformer_dateaccepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationperformer',
            name='dateAccepted',
            field=models.DateTimeField(null=True, verbose_name='Дата принятия'),
        ),
        migrations.AlterField(
            model_name='applicationperformer',
            name='dateDeclined',
            field=models.DateTimeField(null=True, verbose_name='Дата отказа'),
        ),
        migrations.AlterField(
            model_name='applicationperformer',
            name='dateSent',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата отправки'),
        ),
    ]
