# Generated by Django 4.1 on 2023-12-14 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_applicationperformer_dateaccepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='performers',
            field=models.ManyToManyField(blank=True, null=True, related_name='application', through='api.ApplicationPerformer', to='api.sawatzkyemployee', verbose_name='Исполнители'),
        ),
        migrations.AlterField(
            model_name='applicationperformer',
            name='performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sawatzkyemployee'),
        ),
    ]
