# Generated by Django 4.1 on 2023-12-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_application_status_alter_workobjectsgroup_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workobject',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование группы'),
        ),
    ]
