# Generated by Django 4.1 on 2023-12-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_workobject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workobject',
            name='address',
            field=models.CharField(max_length=512, verbose_name='Адрес объекта'),
        ),
        migrations.AlterField(
            model_name='workobject',
            name='code',
            field=models.CharField(max_length=512, verbose_name='Код объекта'),
        ),
        migrations.AlterField(
            model_name='workobject',
            name='contractNumber',
            field=models.CharField(max_length=512, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='workobject',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Наименование группы'),
        ),
        migrations.AlterField(
            model_name='workobjectsgroup',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Наименование группы'),
        ),
    ]
