version: '3.7'

services:

  back: 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env.dev
    command: bash -c "python3 /home/app/web/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
    - static_volume:/home/app/web/staticfiles
    - media_volume:/home/app/web/media 
    - ./:/home/app/web
    
    depends_on:
      - db 

  # react:
  #   build:
  #     context: ../front
  #     dockerfile: ./Dockerfile.dev
  #   env_file:
  #     - ../front/.env.dev
  #   volumes:
  #     - ../front/src:/home/app/front/src
  #   ports:
  #     - 3000:3000


  db:
    image: postgres:12-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
    restart: unless-stopped
    ports: 
      - 5432:5432


  
volumes:
  pg_data:
  static_volume:
  media_volume:
  # react_build: