version: '3'

services: 

  back: 
    build: 
      context: ./
      dockerfile: Dockerfile
    command: daphne -b 0.0.0.0 -p 8000 config.wsgi:application
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
    - back_static:/home/app/back/staticfiles
    - back_media:/home/app/back/media 
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
    networks:
      - app-network


  db:
    image: postgres:12-alpine
    volumes:
      - back_db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    restart: unless-stopped

    networks:
      - app-network


  redis:
      image: redis:latest
      ports:
        - 6379:6379
      networks:
        - app-network


volumes:
  back_static:
    external: true
  back_media:
    external: true
  back_db_data:


networks:
  app-network:
    external: true